### ISSUE TITLE
FFT doesn't produce single spike but produces spikes (on Windows)

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [nikp123/xava#13]
I tested it against other FFT programs and they appear to work correcty.
![Screenshot (1)](https://user-images.githubusercontent.com/17462236/82948851-e2fd7080-9fa2-11ea-9d37-578bcf792dec.png)

**Comment by nikp123** [comment]
Did you test this against a pure sine wave or a sqaure wave?

**Comment by TechAdvancedCyborg** [comment]
pure sine

**Comment by nikp123** [comment]
that's a bug most likely then

**Comment by TechAdvancedCyborg** [comment]
oh

**Comment by nikp123** [comment]
oh, it's on windows. it probably is, since i didn't do much testing on there

**Comment by TechAdvancedCyborg** [comment]
it was a 500hz sine wave if you wanna compare

**Comment by TechAdvancedCyborg** [comment]
is the FFT algorithm different between platforms?

**Comment by nikp123** [comment]
440 Hz on linux fxp
![image](https://user-images.githubusercontent.com/4696350/82949321-af6f1600-9fa3-11ea-88b3-63a39f2fec73.png)
probably is a bug in my WASAPI implementation

**Comment by nikp123** [comment]
note: the lower band is just normal error due to floats and fft being kinda inaccurate

**Comment by TechAdvancedCyborg** [comment]
is the data captured in a different format?

**Comment by nikp123** [comment]
yup, xava has audio input "backends"

**Comment by nikp123** [comment]
each have entirely different implementations

**Comment by TechAdvancedCyborg** [comment]
oh

**Comment by TechAdvancedCyborg** [comment]
btw what desktop do you have?

**Comment by nikp123** [comment]
i3wm

**Comment by TechAdvancedCyborg** [comment]
looks dope

**Comment by nikp123** [comment]
![image](https://user-images.githubusercontent.com/4696350/82949600-30c6a880-9fa4-11ea-8875-6562e4cc3a42.png)
bug seems to be reproducible on wine

**Comment by nikp123** [comment]
but it's nowhere near as bad as in your case

**Comment by TechAdvancedCyborg** [comment]
want me to send my test audio?

**Comment by nikp123** [comment]
i don't need it, i can already see the bug (even on wine)

**Comment by nikp123** [comment]
i did some hacky variable conversions (since apparently m$ uses a different audio data format), might be that

**Comment by TechAdvancedCyborg** [comment]
In the past I have made a "audio visualiser" with python on windows and it has the exact same issue

**Comment by TechAdvancedCyborg** [comment]
gonna try finding a screenshot

**Comment by nikp123** [comment]
was it using fftw as a backend?

**Comment by TechAdvancedCyborg** [comment]
I think

**Comment by TechAdvancedCyborg** [comment]
I was using numpy.fft

**Comment by TechAdvancedCyborg** [comment]
can't find a screenshot but basically the same

**Comment by TechAdvancedCyborg** [comment]
![image](https://user-images.githubusercontent.com/17462236/82952139-b8161b00-9fa8-11ea-97ec-c542c730e1d5.png)
500hz on Ubuntu

**Comment by TechAdvancedCyborg** [comment]
now that is beautiful

**Comment by nikp123** [comment]
turns out i somehow messed up the binary sign value conversion and the [comment i left in my code}(https://github.com/nikp123/xava/blob/6e2f524c79aad60ad07cbbb521b2e1de29d85f16/src/input/wasapi.cpp#L36) was misleading

using portaudio on windows doesn't have this issue... let me investigate how they did it

**Comment by TechAdvancedCyborg** [comment]
so, any progress in your investigation?

**Comment by TechAdvancedCyborg** [comment]
Also why does PortAudio look "chunkier" is the refresh rate lower?

**Comment by TechAdvancedCyborg** [comment]
wow the visualization is super different

**Comment by TechAdvancedCyborg** [comment]
And it was working on my mic but when I set it to my headphones it crashes.

**Comment by TechAdvancedCyborg** [comment]
```   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Internal Microphone (Cirrus Log, MME (2 in, 0 out)
   2 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  3 Headphones (Cirrus Logic CS4208, MME (0 in, 2 out)
   4 Speakers (Cirrus Logic CS4208 (, MME (0 in, 2 out)
   5 1 - PHL 246E7 (2- AMD High Defi, MME (0 in, 2 out)
   6 Digital Audio (S/PDIF) (Cirrus , MME (0 in, 2 out)
   7 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
   8 Internal Microphone (Cirrus Logic CS4208 (AB 128)), Windows DirectSound (2 in, 0 out)
   9 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
  10 Headphones (Cirrus Logic CS4208 (AB 128)), Windows DirectSound (0 in, 2 out)
  11 Speakers (Cirrus Logic CS4208 (AB 128)), Windows DirectSound (0 in, 2 out)
  12 1 - PHL 246E7 (2- AMD High Definition Audio Device), Windows DirectSound (0 in, 2 out)
  13 Digital Audio (S/PDIF) (Cirrus Logic CS4208 (AB 128)), Windows DirectSound (0 in, 2 out)
  14 Speakers (Cirrus Logic CS4208 (AB 128)), Windows WASAPI (0 in, 2 out)
  15 1 - PHL 246E7 (2- AMD High Definition Audio Device), Windows WASAPI (0 in, 2 out)
  16 Headphones (Cirrus Logic CS4208 (AB 128)), Windows WASAPI (0 in, 2 out)
  17 Digital Audio (S/PDIF) (Cirrus Logic CS4208 (AB 128)), Windows WASAPI (0 in, 2 out)
  18 Internal Microphone (Cirrus Logic CS4208 (AB 128)), Windows WASAPI (2 in, 0 out)
  19 SPDIF Out (HD Audio SPDIF out), Windows WDM-KS (0 in, 2 out)
  20 Speakers (HD Audio Speaker), Windows WDM-KS (0 in, 4 out)
  21 Microphone (HD Audio Microphone 2), Windows WDM-KS (2 in, 0 out)
  22 Headphones (HD Audio Headphone), Windows WDM-KS (0 in, 2 out)
  23 Output (AMD HD Audio HDMI out #0), Windows WDM-KS (0 in, 2 out)```

**Comment by nikp123** [comment]
yeah, the thing is portaudio requires a so-called "loopback" device (which is essentially a virtual microphone recording the output of your screen). this required custom drivers and was a mess to set up

cant investigate that much now, but from what i've tried already i'm trying to find out how portaudio corrects the samples properly while recording as it also relies on WASAPI for sound input

turns out WASAPI uses a different sample format (who knew) and you need to do some conversions before you can cram it inside fftw

current sources im investigating atm: https://github.com/EddieRingle/portaudio/blob/9eb5f0b3d820a81d385504d9c54534abbeea1099/src/common/pa_converters.c
https://github.com/EddieRingle/portaudio/blob/9eb5f0b3d820a81d385504d9c54534abbeea1099/src/hostapi/wasapi/pa_win_wasapi.c
https://docs.microsoft.com/en-us/windows/win32/coreaudio/capturing-a-stream

**Comment by nikp123** [comment]
interesting: https://www.thewelltemperedcomputer.com/KB/WASAPI.htm
if that's true, i'm completely wrong

i was essentially cramming a 32-bit float as an int, i have no darn idea how this could've worked in the first place then

**Comment by nikp123** [comment]
jokes on me it was 32bit float all along

**Comment by nikp123** [comment]
main takeaway: research the damn data format before you use it

**Comment by nikp123** [comment]
i'm just more amazed how that code worked in the first place

anyway that's a win64 build with the corrected error
[yes.zip](https://github.com/nikp123/xava/files/4690954/yes.zip)

test it out before i can close this issue, just to make sure it's gone

**Comment by TechAdvancedCyborg** [comment]
not lett

**Comment by TechAdvancedCyborg** [comment]
On load it tells me a whole bunch of DLLs are missing

**Comment by TechAdvancedCyborg** [comment]
libportaudio-2.dll

**Comment by nikp123** [comment]
copy over the dlls from the previous install

**Comment by TechAdvancedCyborg** [comment]
done already it just isn't there

**Comment by TechAdvancedCyborg** [comment]
downloading it

**Comment by nikp123** [comment]
[libportaudio-2.zip](https://github.com/nikp123/xava/files/4691390/libportaudio-2.zip)

**Comment by TechAdvancedCyborg** [comment]
Now it says, `The application was unable to start correctly (0xc000007b). Click OK to close the application.`

**Comment by nikp123** [comment]
use that dll

**Comment by nikp123** [comment]
its probably just a dll mismatch

**Comment by TechAdvancedCyborg** [comment]
yup

**Comment by TechAdvancedCyborg** [comment]
now I need libssp-0

**Comment by TechAdvancedCyborg** [comment]
well I found a libssp dll and I got it running

**Comment by TechAdvancedCyborg** [comment]
there is a visible issue

**Comment by nikp123** [comment]
the same thing?

**Comment by TechAdvancedCyborg** [comment]
no the thing is glitchy

**Comment by TechAdvancedCyborg** [comment]
gonna try filming

**Comment by nikp123** [comment]
guess imma fire up my vm for this

**Comment by TechAdvancedCyborg** [comment]
the spike works

**Comment by TechAdvancedCyborg** [comment]
the issue is the bars are probably out of sync with something

**Comment by TechAdvancedCyborg** [comment]
[XAVA 2020-05-27 22-01-31.zip](https://github.com/nikp123/xava/files/4691472/XAVA.2020-05-27.22-01-31.zip)

**Comment by TechAdvancedCyborg** [comment]
can you provide me with libspp-0.dll?

**Comment by nikp123** [comment]
something is definitely wrong there

**Comment by nikp123** [comment]
or it's just the dithering the guy mentioned (in that website i posted earilier), in which case i LITERALLY cannot make a solution:

anyway dithering is something dumb like:
int value = readValue() + rand(-10, 10);

**Comment by TechAdvancedCyborg** [comment]
No change

**Comment by TechAdvancedCyborg** [comment]
so basically I need to increase my sens?

**Comment by nikp123** [comment]
i mean that happens normally if you lower the smoothing

**Comment by TechAdvancedCyborg** [comment]
i'm at 50 smoothing

**Comment by nikp123** [comment]
"higher values means smoother" meanwhile the default is 85

**Comment by nikp123** [comment]
raise it up to 85 or 90

**Comment by TechAdvancedCyborg** [comment]
same issue no change

**Comment by nikp123** [comment]
same kind of error is observed on linux, so i wouldn't classify this as a issue

**Comment by nikp123** [comment]
[simplescreenrecorder-2020-05-27_22.15.57.zip](https://github.com/nikp123/xava/files/4691543/simplescreenrecorder-2020-05-27_22.15.57.zip)
if you meant the random jumps up and down

**Comment by nikp123** [comment]
oooooohhh

did you turn off vsync?

**Comment by TechAdvancedCyborg** [comment]
yup mine was looking way worse though

**Comment by TechAdvancedCyborg** [comment]
no

**Comment by nikp123** [comment]
just do vsync = 1 just to be sure

**Comment by TechAdvancedCyborg** [comment]
already done

**Comment by nikp123** [comment]
also did you remove the ';'

**Comment by TechAdvancedCyborg** [comment]
yup

**Comment by nikp123** [comment]
same results?

**Comment by TechAdvancedCyborg** [comment]
yup

**Comment by nikp123** [comment]
same happens (as yours) when i fullscreen

turns out it isnt that accurate

just use the ignore option to eliminate the low amplitude errors

**Comment by nikp123** [comment]
basic usage ''ignore = max height of the offending wave in pixels"

**Comment by TechAdvancedCyborg** [comment]
well it removes the low amplitude bars

**Comment by TechAdvancedCyborg** [comment]
looks to me like an issue where the gravity applies itself in a non smooth matter

**Comment by nikp123** [comment]
well issue resolved then? that option exists for those bars in particular, because (by nature) fft is inaccurate so your cpu doesn't end up in smoke

**Comment by TechAdvancedCyborg** [comment]
yeah

**Comment by TechAdvancedCyborg** [comment]
issue closed
