### ISSUE TITLE
On Ubuntu 20.04 libportaudio-dev has no installation candidate...

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [nikp123/xava#15]
Solution:
in `README.md` replace 
```apt-get install libfftw3-dev libasound2-dev libpulse-dev libx11-dev libsdl2-dev libportaudio-dev cmake git```
with
```apt-get install libfftw3-dev libasound2-dev libpulse-dev libx11-dev libsdl2-dev libportaudio2 cmake git```

**Comment by TechAdvancedCyborg** [comment]
Opened PR: https://github.com/nikp123/xava/pull/16

**Comment by nikp123** [comment]
It's resolved now. Thank you for finding this issue and providing a fix.
