### ISSUE TITLE
Improve CPU Usage

### ISSUE THREAD

**Issue by ForeverZer0** [nikp123/xava#2]
Looks promising, but would it be possible to make some improvements for the CPU usage? Not sure if is empty cycles or not, but it maxes out a core on an Intel i7-7700HQ @ 8x 3.8GHz (just using default settings). 

That is quite a bit for a basic app to be using, especially one intended simply for background aesthetics.

**Comment by nikp123** [comment]
Are you using nvidia graphics

**Comment by ForeverZer0** [comment]
Thanks, will give that a try that when I get a chance, will let you know what effect it has. 

To answer your question, yes, I am have a Nvidia GPU with proprietary drivers, as the nouveaur ones have not worked well (at all) with my particular machine, at least at the time I installed my system. The open-source drivers would just cause the hanging "Reached Graphical Interface" message on boot.

Have a GeForce GTX 1060, 3GB, latest drivers (418.56).

**Comment by nikp123** [comment]
@ForeverZer0 try disabling VSync in the nvidia control panel

**Comment by ForeverZer0** [comment]
@nikp123 Disabled VSync, and it dropped total CPU from 12% (1 core) down to 4%, so it does appear to related xD.

**Comment by nikp123** [comment]
@ForeverZer0 Try the new version, but I expect it to work because I no longer have a CPU capping at 100% when running the new build on my 960M.

For others: If you see tearing issues, open a new issue asking for proper Vsync support.

**Comment by nikp123** [comment]
Definitely fixed in 85281b593d1d4c2831acbb140cef065001d07b25

For future devs: You need to override ``__GL_YIELD`` environment variable and set it to ``USLEEP``

If there are any more issues, feel free to comment so I can reopen this issue.

**Comment by ForeverZer0** [comment]
Totally forgot to give you a reply to this, but I did test, and it does seem to fix the issue. :)

**Comment by nikp123** [comment]
@ForeverZer0 btw you can use Vsync now, it's just that it uses a "less-than-optimal" way of handling it by default
