### ISSUE TITLE
[Bug] Constantly reloads

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [nikp123/xava#20]
Due to commit 568771a92c2d8c0cc9dfa279aa919de00aa5577f XAVA constantly reloads as if the display changes but it doesn't.

OS: Ubuntu 20.04 with KDE
Monitors: 2x(1920x1080)

```
ontake@ontake-PC:~/Apps/xava/xava/build$ xava
Display change detected - Restarting...
Display change detected - Restarting...
Display change detected - Restarting...
Display change detected - Restarting...
Display change detected - Restarting...
Display change detected - Restarting...
```

**Comment by TechAdvancedCyborg** [comment]
I would suggest an option in the config to ignore display change.

**Comment by nikp123** [comment]
Yeah, sounds pretty unusable otherwise. Thanks for reporting.

**Comment by nikp123** [comment]
Test if it works.
*I mean it probably should*, but test anyway.

I don't consider this to be the "true" solution, but it will do for now. I'm just curious as to why are ```RRScreenChangeNotify``` events firing constantly as opposed to just when the display (is well changed). I will have to look into this, probably some downstream bug I'd imagine.

**Comment by TechAdvancedCyborg** [comment]
Yes, building rn.

**Comment by TechAdvancedCyborg** [comment]
For some reason, it keeps doing the same thing, looking into it.

**Comment by TechAdvancedCyborg** [comment]
Can you try changing monitors on new build?

**Comment by iamsubhranil** [comment]
yup, changing `reload_on_display_configure = false` is not solving the issue.

**Comment by nikp123** [comment]
The issue seems to be fixed. Tested on Kubuntu 20.04 with Intel graphics.

Please check if everything seems to work on your end. Try checking if you have missed any steps.

**Comment by TechAdvancedCyborg** [comment]
will do!

**Comment by nikp123** [comment]
Did you reproduce the issue?

**Comment by TechAdvancedCyborg** [comment]
Nope, it is fixed, sorry for the long response...
