### ISSUE TITLE
Some bars don't work properly (in some cases)

### ISSUE THREAD

**Issue by Ishi-Inanis** [nikp123/xava#29]
Some of the lanes do not work. Config has not changed yet. What could be the error or how to solve it?
P. S. appears when 67 or more lanes
![Screenshot_20201019_181730](https://user-images.githubusercontent.com/26205392/96471239-c99ddf00-1237-11eb-98d0-824774858405.png)

**Comment by nikp123** [comment]
can you send the config? makes it way easier to solve/debug

**Comment by Ishi-Inanis** [comment]
During this time I changed it, but here
[config.txt](https://github.com/nikp123/xava/files/5408871/config.txt)
P. S. if the number is increased to 67, then 3 non-working lanes appear

**Comment by nikp123** [comment]
```
1: 26.000000 -> 27.000000 (9 -> 9)
2: 27.000000 -> 29.590765 (10 -> 9)
3: 29.590765 -> 33.825756 (10 -> 11)
4: 33.825756 -> 39.951958 (12 -> 13)
5: 39.951958 -> 48.323807 (14 -> 16)
6: 48.323807 -> 59.396534 (17 -> 21)
7: 59.396534 -> 73.734917 (22 -> 26)
8: 73.734917 -> 92.029251 (27 -> 33)
9: 92.029251 -> 115.117027 (34 -> 41)
10: 115.117027 -> 144.009705 (42 -> 52)
```

Frequency separator is broken lol

**Comment by nikp123** [comment]
``2: 27.000000 -> 29.590765 (10 -> 9)``

you can see the bug here, will make the fix pretty quickly

**Comment by nikp123** [comment]
Try now, it was indeed a nasty little bug.

**Comment by TechAdvancedCyborg** [comment]
@nikp123 can you send a Windows build for that, please?

**Comment by nikp123** [comment]
Anyways just replace the two files [build-win-release.zip](https://github.com/nikp123/xava/files/5409339/build-win-release.zip)

**Comment by TechAdvancedCyborg** [comment]
Thx

**Comment by TechAdvancedCyborg** [comment]
Some dll mismatches... Can you send me all the DLLs included with the build?

**Comment by nikp123** [comment]
[win32-rel.zip](https://github.com/nikp123/xava/files/5410116/win32-rel.zip)
here you go, just the installer is broken, dont use it

**Comment by TechAdvancedCyborg** [comment]
yup the build fixes the issue for me

**Comment by TechAdvancedCyborg** [comment]
![image](https://user-images.githubusercontent.com/17462236/96628926-2c17dd80-1313-11eb-91e2-d098ae2c7684.png)

**Comment by nikp123** [comment]
I'm going to assume it works on your machine as well. Closing issue
