### ISSUE TITLE
Y-axis adjustment.

### ISSUE THREAD

**Issue by SinisterBrain** [nikp123/xava#3]
Thanks for the wonderful program!  
Just updated to xava-git (0.6.2.1.r0.g960965b-1) and it no longer sits on the taskbar (Manjaro KDE).  So I thought I'd open the config and tinker with the y-axis.  Forgive my ignorance but I can put in negative values correct?  

```
# Additionally we can further adjust the positions if needed (in pixels)
; x_padding = 0
 y_padding = -50
```
Unfortunately if that's the case it doesn't move the bars down to close the gap.  positive values however work fine. :) If not, then I'm a dummy and sorry I wasted your time.
I had it set in the previous version to bottom_right and it rested on the bar.  
I also tried `alignment = 'none'` and adjusted the y-axis, no luck.  I also drug it to rest on the bar but it doesn't save the position because it popped back to it's spot with the gap.

Here's a screenshot if that's helpful.

![Imgur](https://i.imgur.com/gtL5wMy.png)

Thank you for your time.

**Comment by nikp123** [comment]
I actually was thinking if the padding bahaviour should be relative or based upon alignment.

So if you don't mind sharing your thoughts, I just going to ask what behaviour is best in your opinion.

So lets have alignment set to 'bottom'.
It'll spawn the window on the bottom and the y-padding is reversed because its y pixels from the bottom, this is how it's currently implemented and I can easily change this if you so choose.
And relative would be that the window is adjusted relative to desktop space (fxp. Negative y_padding will always move the window up, and so on)

To explain your example that you have provided, with the current behavior and alignment set to bottom or even without setting it, it would spawn the window out of bounds when you put negative y_padding.

bottom sets window to screen_height-y_padding (with it being negative, it wont spawn the window there because it was out of bounds)

And setting alignment to none still produces issues because you spawned the window in negative coordinates and its still out of bounds.

So should I keep this behaviour or change it to behave like you expected (relative)?

Sorry for the wall of text this is just one of design descisions that I'm still unsure if they're right?

**Comment by SinisterBrain** [comment]
Thank you for your response and the explanation of the y options.  
If I understand you correctly, in the current implementation a `y_padding = 0` (or with it commented out) will place Xava directly on the bottom of the screen or directly on top of the taskbar in my case.

To be honest I prefer it in the current implementation.  I'm sure it would save you headaches as well with issues of people asking what happened to a now out of bounds Xava after they put a `y_padding = -300`.  :)

However, for some reason Xava is no longer obeying a commented out `y_padding` or `y_padding = 0` with an `alignment = bottom_right`.

As I was looking at my config for Xava.  I'm wondering if for some reason Xava thinks the border is still active?  It's looks to be the exact size for the border. I have it set to `border = 0` normally.  Though I did turn it on to see, it looks about the same size as the gap but it's hard to tell.

Again, thank you for your reply and detailed explanation.  I appreciate it.  
I hope my reply is as helpful.  

Hope you have a nice day!

**Comment by nikp123** [comment]
oh it might be just a thing with iniparser
try to put it in single quotes ``'``, see if it changes anything

**Comment by SinisterBrain** [comment]
No change in the gap.  with `'` or without.  
Just for the fun of it I tried it on `alignment = bottom_right` with and without
And also on `y_padding = 0` just to be sure.
Each time I saved the config.  Then closed Xava and restarted it.  I did that instead of hitting the <kbd>r</kbd>.  Might have the same effect but I wanted to be sure.

**Comment by nikp123** [comment]
do you mind if I contact you in some way like discord, irc, whatever do discuss this issue

because i still feel like i didn't explain the behavior to you properly

discord: nik123#6236

**Comment by SinisterBrain** [comment]
Apologies, it's been a little crazy for me.  Hadn't had time to get back to this.
I don't have discord (I know, strange) but it's easy enough to make one I'd assume.
This machine doesn't have a mic (desktop) as I never use it anyway, but if you like I can make a discord.
Honestly I think you explained it fine.  I did a little extra reading and I think I have a grasp of how it works now.  The relative screen space is a little confusing to be honest.  
Anyway, thanks for offering to explain it.

**Comment by nikp123** [comment]
If you are sure that you know how it behaves. Are you still experiencing unusual behaviour if not should I change it (since it might be confusing for other people)?

**Comment by SinisterBrain** [comment]
Hi, Yes I'm still experiencing the behavior.  With the default config you include, for whatever reason on a brand new install (The pic I attached in my previous post) I don't understand it simply will not sit flush against the bottom of the screen anymore.  There's always the few pixel gap.  

The really strange thing is I installed the Windows version and it did the same thing.
I'm starting to wonder if my computers are evil or something?

**Comment by nikp123** [comment]
@SinisterBrain alignment to bottom and dont touch the paddings (leave them as is)

**Comment by nikp123** [comment]
if it doesnt work then we have a problem

**Comment by nikp123** [comment]
oh wait, shadows

**Comment by SinisterBrain** [comment]
Align to bottom - ✔
x and w padding commented out and 0 - ✔
Shadows off - ✔

Still the gap.  I never see it because I usually have dark wallpapers.  I loaded something a little brighter as a wallpaper and even with shadows off (Not only commented out but with a 0) there's a shadow at the bottom too.  
Tried it on all 3 computers.  Same thing, no effect.  Still the weird gap.
Sorry!

**Comment by nikp123** [comment]
setting shadow size to 0 is the only way to disable shadows

**Comment by SinisterBrain** [comment]
Removing the # on the new install (Laptop) fixed it.
However removing it from the machine that was upgraded doesn't fix it.

Maybe I just need to use the newer config?

**Comment by SinisterBrain** [comment]
Fixed it.

I used the new config from your example files.  I simply put my color for the gradient, a couple of small tweaks I did and left padding alone.  I also took out the `;` in the example config on the shadow entry and now it sits beautifully like it did before on the taskbar!  YAY!
So it was something definitely in my older config that was messing it up.

![Imgur](https://i.imgur.com/XEig47G.png)

I'm just so happy now!
Thank you so much for your patience @nikp123 and explanation.  
***
Totally unrelated.  I've been reading over the config files for a very long time now and I noticed a few little errors.  Mostly misspellings.  Can I make those edits here and submit them to you?  If you don't mind that is.  
Also, you said you deprecated `#` and `;` for shadow but it's in the example config.  Unless I misunderstood.

**Comment by nikp123** [comment]
For the ``#`` or ``;``, they don't work because the shadow is set on by default and by commenting out the value, you make it get the default value (which are hard-coded in the code and they change by platform/OS)

**Comment by SinisterBrain** [comment]
Understood.  
Thank you again.

**Comment by nikp123** [comment]
These commits should resolve this issue for others.

If there's still something not behaving as expected, comment on this issue.

Closing for now
