### ISSUE TITLE
malloc errror on running xava

### ISSUE THREAD

**Issue by shivanshu-semwal** [nikp123/xava#30]
On running xava i get the following error
```
xava: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
[1]    29899 abort (core dumped)  xava
```

`xava` version = `xava 0.6.3.1`
I used the default `config` file.
I installed it from AUR given in the README [https://aur.archlinux.org/packages/xava-git/](https://aur.archlinux.org/packages/xava-git/)

**Comment by nikp123** [comment]
Thanks for reporting.

On a another note: *I really need a unstable branch, because this happens quite often ngl*

Note 2: I already fixed this in https://github.com/nikp123/xava/commit/858e6e73066bab80906fb49f3d500716fae781cc, just forgot to push the update, my bad.

**Comment by nikp123** [comment]
Please test and just reply letting me know if it works now.

**Comment by shivanshu-semwal** [comment]
> Please test and just reply letting me know if it works now.

Thanks it works now.
