### ISSUE TITLE
XQuartz 2.7.11 doesn't work.

### ISSUE THREAD

**Issue by satyrnhub** [nikp123/xava#32]
The 2.7.11 version of `XQuartz`, which is the only one that will launch properly (in my case), doesn't work due to using a version of `libX11` older than 11.0.0. Not sure if there is much to fix here, as I don't know if `xava` will work on older `libX11` versions. Will try to test this soon.

**Comment by nikp123** [comment]
disable transparency and opengl

if that doesnt work use SDL as the output

**Comment by satyrnhub** [comment]
> disable transparency and opengl
> 
> if that doesnt work use SDL as the output

Didn't work, also used SDL, still nope. I will try the latest alpha instead. Alpha 4 came out last night, and I was previously having issues with alpha 3.

**Comment by satyrnhub** [comment]
IT WORKS!
