### ISSUE TITLE
[feature request] ability to specify output screen

### ISSUE THREAD

**Issue by dikeert** [nikp123/xava#35]
Thank you so much for contributing into this project and providing us with awesome visualiser that is easy on CPU (everything else is much hard on CPU).

The addition of override_redirect makes it almost perfect. Now if only I could move it to another monitor of mine.

**Comment by nikp123** [comment]
That feature is already in the wayland fork, so porting it back to X11 seems like a logical thing to do. Updates are going to be posted here. Also the ``unstable`` branch is filled with a lot of new things, I'll have to merge that too before doing anything.

**Comment by dikeert** [comment]
Btw, for whoever else whats to move it to the other screen, you can still do that, you just need to guess offsets correctly. 

I've got 4k primary monitor on the left and small FHD monitor on my lapton on the right, I was able to move XAVA to my laptop screen like this:


```
alignment = 'bottom_left'
x_padding = 3840
 y_padding = 1080
```

**Comment by nikp123** [comment]
Yeah I thought you might notice that too

**Comment by nikp123** [comment]
That's a workaround since the coordinate space is global and in essence acts as one big monitor.

**Comment by nikp123** [comment]
aka. all the screen spaces are added together to make the global space, with the beginning being in the top-left (0,0)

**Comment by nikp123** [comment]
Feature done. Just do some testing (just to make sure), although I believe it is done and this could be closed.

You have to download the unstable branch by:
```
git checkout unstable
git pull origin unstable
```
within the XAVA git directory

**Comment by dikeert** [comment]
Hmmm, unstable branch to be ignoring `override_redirect`, so I can't really test it.

**Comment by nikp123** [comment]
The config has been changed.
Look into examples_files dir within the unstable branch.

**Comment by dikeert** [comment]
With update config it works perfectly, thank you very much!

**Comment by dikeert** [comment]
Config of the dream:

```
[x11]
 override_redirect = true
 monitor_name = eDP-1-1
```
