### ISSUE TITLE
CMake Error at CMakeLists.txt

### ISSUE THREAD

**Issue by banancc** [nikp123/xava#4]
I tryed to install xava and that happened:
`cmake .. -DCMAKE_BUILD_TYPE=Release
`
```
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- iniparser not found on system, building from source.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Checking for module 'fftw3'
--   Found fftw3, version 3.3.7
-- Not a Windows platform, can use POSIX now!
-- portaudio library not found
-- Configuring done
CMake Error at CMakeLists.txt:27 (add_library):
  Cannot find source file:

    lib/iniparser/src/dictionary.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:27 (add_library):
  No SOURCES given to target: iniparser


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Please help!
Thanks!

**Comment by nikp123** [comment]
``fatal: not a git repository (or any parent up to mount point /)``

This shouldn't happen.....

**Comment by nikp123** [comment]
Try cloning the repository instead of downloading it

**Comment by banancc** [comment]
> Try cloning the repository instead of downloading it

It's still the same :(

**Comment by nikp123** [comment]
Can't reproduce. Do you mind sharing your configuration?

Workaround: try installing iniparser independently.

**Comment by banancc** [comment]
> Do you mind sharing your configuration?

Intel® Pentium(R) CPU G6950 @ 2.80GHz × 2 
integrated graphics

**Comment by nikp123** [comment]
Apologies, I meant OS/distro.

**Comment by nikp123** [comment]
Also interesting to note is:
```
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Are you using a remote filesystem by any chance?


Try 
```
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
```

Before running cmake.

**Comment by banancc** [comment]
> Apologies, I meant OS/distro.

Ubuntu Budgie 18.04.3 LTS

**Comment by banancc** [comment]
> Are you using a remote filesystem by any chance?

Nop

**Comment by banancc** [comment]
> Try below before running cmake.
> 
> ```
> export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
> ```

```
cmake .. -DCMAKE_BUILD_TYPE=Release 
-- iniparser not found on system, building from source.
fatal: not a git repository (or any of the parent directories): .git
-- Not a Windows platform, can use POSIX now!
-- portaudio library not found
-- Configuring done
CMake Error at CMakeLists.txt:27 (add_library):
  Cannot find source file:

    lib/iniparser/src/dictionary.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:27 (add_library):
  No SOURCES given to target: iniparser


CMake Generate step failed.  Build files cannot be regenerated correctly.

```

**Comment by nikp123** [comment]
are you sure there's a ``.git`` folder in the root directory of the project?

fxp. ``/home/banancc/Downloads/xava/.git``

because that's really not supposed to happen.....

**Comment by banancc** [comment]
> are you sure there's a `.git` folder in the root directory of the project?

![Screenshot from 2019-08-24 17-41-48](https://user-images.githubusercontent.com/47900972/63638912-9f35ad80-c696-11e9-8327-62ac18bc1150.png)

I think yes

**Comment by nikp123** [comment]
xava-master - thats the zip file (not clone)

**Comment by nikp123** [comment]
But I'll try to fix it for those who hadn't cloned anyway

**Comment by banancc** [comment]
> xava-master - thats the zip file (not clone)

so i need to just zip it right?

**Comment by nikp123** [comment]
No just do the following in the terminal:
```
git clone https://github.com/nikp123/xava
```

**Comment by banancc** [comment]
![Screenshot from 2019-08-24 18-19-47](https://user-images.githubusercontent.com/47900972/63639443-c8a50800-c69b-11e9-823e-f60583c201a6.png)

I'm too dumb for that or what? :|

**Comment by nikp123** [comment]
try that but with ``export GIT_DISCOVERY_ACROSS_FILESYSTEM=1``

**Comment by banancc** [comment]
> export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

when i need to type that command?

**Comment by nikp123** [comment]
just before you run cmake

**Comment by banancc** [comment]
I replaced my cmakelists.txt with the one you attached

**Comment by banancc** [comment]
> just before you run cmake

```
-- iniparser not found on system, building from source.
fatal: not a git repository (or any of the parent directories): .git
-- Not a Windows platform, can use POSIX now!
-- portaudio library not found
-- Configuring done
CMake Error at CMakeLists.txt:27 (add_library):
  Cannot find source file:

    lib/iniparser/src/dictionary.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:27 (add_library):
  No SOURCES given to target: iniparser


CMake Generate step failed.  Build files cannot be regenerated correctly.

```

**Comment by nikp123** [comment]
i seriously have no idea whats going on......

if you are mistaking any steps, ill just write them down:
```
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
git clone https://github.com/nikp123/xava
mkdir -p xava/build
cd xava/build
cmake ..
make -j$(nproc)
```

and that should be it. If that fails, then I seriously have no idea.
Since I cannot reproduce that issue in any shape or form.

**Comment by banancc** [comment]
> EDIT: You're trying to run cmake in a wrong directory. Of course it's going to fail. You forgot to `cd xava` before you did the `mkdir` command.

Thanks a lot! :)
But now i have that:
```
qwerty@ubuntu:~/xava/build$ make -j$(nproc)
make: *** No targets specified and no makefile found.  Stop.

```

**Comment by nikp123** [comment]
did cmake succeed?

**Comment by banancc** [comment]
I deleted all xava files on my pc and started again with 

> Do these steps instead:

these commands and all worked fine!

Thanks a lot for your support!
![Screenshot from 2019-08-25 18-23-52](https://user-images.githubusercontent.com/47900972/63652131-8ba54800-c765-11e9-8766-4a812ad83cd4.png)

**Comment by banancc** [comment]
So how can i run xava on my desktop? Or i need something more?

**Comment by nikp123** [comment]
just do ``./xava``

or to install do: ``make install``

**Comment by banancc** [comment]
```

qwerty@ubuntu:~/xava/build$ cmake ..
-- iniparser not found on system, building from source.
-- Not a Windows platform, can use POSIX now!
-- portaudio library not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qwerty/xava/build
qwerty@ubuntu:~/xava/build$ make -j$(nproc)
[ 21%] Built target iniparser
[100%] Built target xava
qwerty@ubuntu:~/xava/build$ make install
[ 21%] Built target iniparser
[100%] Built target xava
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/bin/xava
CMake Error at cmake_install.cmake:47 (file):
  file INSTALL cannot copy file "/home/qwerty/xava/build/xava" to
  "/usr/local/bin/xava".


Makefile:117: recipe for target 'install' failed
make: *** [install] Error 1
qwerty@ubuntu:~/xava/build$ 






```

**Comment by nikp123** [comment]
you need to run it as sudo

**Comment by banancc** [comment]
![Screenshot from 2019-08-25 19-06-38](https://user-images.githubusercontent.com/47900972/63652674-821ede80-c76b-11e9-9ae3-bc95479dafe7.png)
OMG! It works! Thanks a lot! I hope to understand how to configure it!
