### ISSUE TITLE
Gradient mode, strange lines inside bars.

### ISSUE THREAD

**Issue by shivanshu-semwal** [nikp123/xava#40]
![image](https://user-images.githubusercontent.com/53912074/127468055-041c11b2-a528-43c7-a0c1-830bff1e27f2.png)
![image](https://user-images.githubusercontent.com/53912074/127468075-ed60ab46-4a29-4780-90b3-2b8de6f33eac.png)

I just change the gradient part form the default config, rest everything is same.

**Comment by nikp123** [comment]
![image](https://user-images.githubusercontent.com/4696350/127469485-1d021341-9733-4be9-9965-b9ec75d10648.png)
cannot reproduce

**Comment by shivanshu-semwal** [comment]
Three colors work fine, but on increasing `gradient_count` above three this problem occur for me.

**Comment by shivanshu-semwal** [comment]
I figured the issue, it was with tiling mode, not in the floating mode.

**Comment by nikp123** [comment]
Interesting how it can be window manager related....

**Comment by shivanshu-semwal** [comment]
So it happen when I resize window in the vertical direction, on stretching it enough it shows those lines, even in floating mode.
