### ISSUE TITLE
[Arch] Xava crashes with stereo option enabled

### ISSUE THREAD

**Issue by ExperiBass** [nikp123/xava#45]
System info:
- EndeavourOS Rolling
- Xava v0.7.0.0

Error:
```
[ERROR] xavaFilterHandleConfiguration at src/filters/default/main.c:399 - 'oddoneout' and stereo channels do not work together!
at /usr/lib/xava/filter_default.so(xavaFilterHandleConfiguration+0x473) [0x7fd644d4afb3]
at xava(+0x2624) [0x5631e9028624]
at /usr/lib/libc.so.6(+0x2d310) [0x7fd645002310]
at /usr/lib/libc.so.6(__libc_start_main+0x81) [0x7fd6450023c1]
at xava(+0x2b7e) [0x5631e9028b7e]
```

Config file attached,
[config.txt](https://github.com/nikp123/xava/files/8188877/config.txt)

**Comment by nikp123** [comment]
Not a crash, more of a config error.
"'oddoneout' and stereo channels do not work together!"

But if this message is kinda misleading I could try implementing an dialog box explaining the error.

**Comment by nikp123** [comment]
Maybe a "oddoneout and stereo cannot be enabled together would explain that"
or just leaving oddoneout disabled automatically when stereo is enabled.

**Comment by ExperiBass** [comment]
> Maybe a "oddoneout and stereo cannot be enabled together would explain that"
> 
> or just leaving oddoneout disabled automatically when stereo is enabled.

I must've overlooked the oddoneout option, and auto-disable would be pretty cool. I'll be opening another issue for the various segfaults I get while tweaking.

**Comment by nikp123** [comment]
actually isn't even a seg fault, its just a backtrace i'd use for potential debugging

**Comment by nikp123** [comment]
anyway i'd have to dump a huge 0.7.1.0 release already
it has over a 200 commit backlog and getting bigger

**Comment by ExperiBass** [comment]
Oh boi big update

**Comment by nikp123** [comment]
```c
#define CONFIG_OPTION(T, name) \
   T name; bool name##_is_set_from_file

#define OPTION_IS_SET(cfg, name) cfg.name##_is_set_from_file

#define CONFIG_SET(cfg, name, value) \
   cfg.name = value; cfg.name##_is_set_from_file = true

typedef struct Config {
   CONFIG_OPTION(int, some_int);
   CONFIG_OPTION(float, some_float);
} Config;

Config parse_config()
{
   Config result = {0};

   CONFIG_SET(some_option, 41432);
}
```
potential solution for future nik

**Comment by nikp123** [comment]
it's been fixed now. not in a good way, but it should prevent xava from getting obscure errors.

**Comment by nikp123** [comment]
Yeah closing this as there's no point for keeping this issue open.
