### ISSUE TITLE
[Arch] Segfault when uncommenting EQ params

### ISSUE THREAD

**Issue by ExperiBass** [nikp123/xava#46]
Interesting issue, xava segfaults when the eq params are uncommented. Comment them and it's perfectly happy to run. Config below:

```
[general]
framerate = 60
vsync = -1
bars = 0
bar_width = 13
bar_spacing = 0

[window]
width = 2560
height = 1560
fullscreen = false
border = false
transparency = true
keep_below = true
interactable = false
taskbar_icon = false

[x11]
root_window = true
override_redirect = true

[gl]
pre_shaderpack = default
post_shaderpack = default
resolution_scale = 1.0
[input]
method = pulseaudio
source = auto
size = 12

[output]
method = x11
channels = stereo

[color]
background = default
foreground = '#1B81F3'
foreground_opacity = 0.5
gradient_count = 0

[filter]
lower_cutoff_freq = 20
higher_cutoff_freq = 15000
integral = 80
monstercat = 0
waves = 5
gravity = 100
log = 1.2
oddoneout = false
eq_balance = 0.6
fft_size = 14
autosens = true
overshoot = -50

[eq]
;1 = 1 # bass
;2 = 1
;3 = 1 # midtone
;4 = 1
;5 = 1 # treble
```

**Comment by nikp123** [comment]
The fix was simple, sorry about the delay. Please check whether it works or not.

**Comment by ExperiBass** [comment]
seems to crash when its in stereo instead of mono, something about it failing to reallocate memory.

```
[ERROR] xavaFilterApply at /home/ging/Builds/xava/src/filters/default/main.c:126 - Failed to reallocate memory
at /usr/lib/xava/filter_default.so(xavaFilterApply+0x9c) [0x7fdb6c378cce]
at xava(+0x44a6) [0x55cc97d224a6]
at /usr/lib/libc.so.6(+0x2d310) [0x7fdb6caa7310]
at /usr/lib/libc.so.6(__libc_start_main+0x81) [0x7fdb6caa73c1]
at xava(+0x2335) [0x55cc97d20335]
```

other than that, eq works :D

**Comment by nikp123** [comment]
> seems to crash when its in stereo instead of mono, something about it failing to reallocate memory.
> 
> ```
> [ERROR] xavaFilterApply at /home/ging/Builds/xava/src/filters/default/main.c:126 - Failed to reallocate memory
> at /usr/lib/xava/filter_default.so(xavaFilterApply+0x9c) [0x7fdb6c378cce]
> at xava(+0x44a6) [0x55cc97d224a6]
> at /usr/lib/libc.so.6(+0x2d310) [0x7fdb6caa7310]
> at /usr/lib/libc.so.6(__libc_start_main+0x81) [0x7fdb6caa73c1]
> at xava(+0x2335) [0x55cc97d20335]
> ```
> 
> other than that, eq works :D

Fixed that as well.

**Comment by ExperiBass** [comment]
yep, works fine :D
