### ISSUE TITLE
Xava's problem with compiling 

### ISSUE THREAD

**Issue by EvilBoi123** [nikp123/xava#48]
I followed the instruction one by one, but I failed to compiling when I reached the "make" part 

I'm in an arch linux. Oh yea, btw I have problem to install it through aur too, idk why

[  1%] Building C object CMakeFiles/iniparser.dir/lib/iniparser/src/dictionary.c.o
[  2%] Building C object CMakeFiles/iniparser.dir/lib/iniparser/src/iniparser.c.o
[  3%] Linking C static library libiniparser.a
[  3%] Built target iniparser
[  4%] Building C object CMakeFiles/xava-shared.dir/src/shared/log.c.o
[  5%] Building C object CMakeFiles/xava-shared.dir/src/shared/config/config.c.o
[  6%] Building C object CMakeFiles/xava-shared.dir/src/shared/module/abstractions.c.o
[  7%] Building C object CMakeFiles/xava-shared.dir/src/shared/ionotify.c.o
[  8%] Building C object CMakeFiles/xava-shared.dir/src/shared/io.c.o
[  9%] Building C object CMakeFiles/xava-shared.dir/src/shared/version.c.o
[ 10%] Building C object CMakeFiles/xava-shared.dir/src/shared/module/unix.c.o
[ 11%] Building C object CMakeFiles/xava-shared.dir/src/shared/io/unix.c.o
[ 12%] Linking C shared library libxava-shared.so
[ 12%] Built target xava-shared
[ 12%] Building C object CMakeFiles/cairo_bars.dir/src/output/shared/cairo/modules/bars/main.c.o
[ 13%] Building C object CMakeFiles/cairo_bars.dir/src/output/shared/cairo/modules/shared/config.c.o
[ 14%] Linking C shared library cairo/module/bars/module.so
[ 14%] Built target cairo_bars
[ 15%] Building C object CMakeFiles/cairo_kinetic.dir/src/output/shared/cairo/modules/kinetic/main.c.o
[ 16%] Linking C shared library cairo/module/kinetic/module.so
[ 16%] Built target cairo_kinetic
[ 16%] Building C object lib/kiss-mpris-properties/src/CMakeFiles/kiss-mpris.dir/kiss-mpris.c.o
[ 17%] Linking C static library libkiss-mpris.a
[ 17%] Built target kiss-mpris
[ 18%] Building C object CMakeFiles/cairo_media_info.dir/src/output/shared/cairo/modules/media_info/main.c.o
/home/cancel/xava/src/output/shared/cairo/modules/media_info/main.c: In function ‘xava_cairo_module_draw_artwork’:
/home/cancel/xava/src/output/shared/cairo/modules/media_info/main.c:296:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
  296 |             if(artwork->image->h > artwork->image->w) {
      |               ^
/home/cancel/xava/src/output/shared/cairo/modules/media_info/main.c:299:9: note: here
  299 |         case ARTWORK_PRESERVE:
      |         ^~~~
[ 19%] Building C object CMakeFiles/cairo_media_info.dir/src/output/shared/util/media/artwork.c.o
[ 20%] Building CXX object CMakeFiles/cairo_media_info.dir/src/output/shared/util/media/artwork_taglib.cpp.o
[ 21%] Building C object CMakeFiles/cairo_media_info.dir/src/output/shared/util/media/media_data.c.o
[ 22%] Linking CXX shared library cairo/module/media_info/module.so
[ 22%] Built target cairo_media_info
[ 23%] Building C object CMakeFiles/cairo_oscilloscope.dir/src/output/shared/cairo/modules/oscilloscope/main.c.o
[ 23%] Building C object CMakeFiles/cairo_oscilloscope.dir/src/output/shared/cairo/modules/shared/config.c.o
[ 24%] Linking C shared library cairo/module/oscilloscope/module.so
[ 24%] Built target cairo_oscilloscope
[ 25%] Building C object CMakeFiles/cairo_stars.dir/src/output/shared/cairo/modules/stars/main.c.o
[ 26%] Building C object CMakeFiles/cairo_stars.dir/src/output/shared/cairo/modules/shared/config.c.o
[ 27%] Linking C shared library cairo/module/stars/module.so
[ 27%] Built target cairo_stars
[ 28%] Building C object CMakeFiles/filter_default.dir/src/filters/default/main.c.o
[ 29%] Linking C shared library filter_default.so
[ 29%] Built target filter_default
[ 30%] Generating ../src/output/graphical_wayland/gen/xdg-shell-client-protocol.h
[ 31%] Generating ../src/output/graphical_wayland/gen/wlr-layer-shell-unstable-v1-client-protocol.c
[ 32%] Generating ../src/output/graphical_wayland/gen/wlr-layer-shell-unstable-v1-client-protocol.h
[ 32%] Generating ../src/output/graphical_wayland/gen/wlr-output-managment-unstable-v1.c
[ 33%] Generating ../src/output/graphical_wayland/gen/wlr-output-managment-unstable-v1.h
[ 34%] Generating ../src/output/graphical_wayland/gen/xdg-output-unstable-v1-client-protocol.c
[ 35%] Generating ../src/output/graphical_wayland/gen/xdg-output-unstable-v1-client-protocol.h
[ 36%] Generating ../src/output/graphical_wayland/gen/xdg-shell-client-protocol.c
[ 37%] Building C object CMakeFiles/out_wayland_opengl.dir/src/output/graphical_wayland/main.c.o
In file included from /home/cancel/xava/src/output/shared/gl/egl.h:7,
                 from /home/cancel/xava/src/output/graphical_wayland/main.h:6,
                 from /home/cancel/xava/src/output/graphical_wayland/main.c:12:
/home/cancel/xava/src/output/shared/gl/main.h:18:14: fatal error: GL/glew.h: No such file or directory
   18 |     #include <GL/glew.h>
      |              ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/out_wayland_opengl.dir/build.make:108: CMakeFiles/out_wayland_opengl.dir/src/output/graphical_wayland/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:364: CMakeFiles/out_wayland_opengl.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I hope someone knows betters, cheers!

**Comment by nikp123** [comment]
Try installing GLEW then recompling

**Comment by EvilBoi123** [comment]
> Try installing GLEW then recompling

it worked! thanks!
