### ISSUE TITLE
[AUR] xava-git ASSERT issue

### ISSUE THREAD

**Issue by cirfis** [nikp123/xava#51]
upon attempting to update xava-git I received this confounding error...

[ 98%] Linking C executable xava
/usr/bin/ld: libxava-shared.so: undefined reference to `assert'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xava.dir/build.make:114: xava] Error 1
make[1]: *** [CMakeFiles/Makefile2:816: CMakeFiles/xava.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by nikp123** [comment]
Should be fixed now.

**Comment by cirfis** [comment]
Holy smokes, that was fast! Works great, as usual, thank you.

**Comment by cirfis** [comment]
may have spoken too soon?

xava-git/src/xava/src/shared/io/io.c:220: xavaFindAndCheckFile: Assertion `(*actualPath) == NULL' failed.
[1]    85149 IOT instruction (core dumped)  xava

**Comment by nikp123** [comment]
Try again please.

**Comment by cirfis** [comment]
The level of support is impressive, thank you! Works perfectly this time.

**Comment by nikp123** [comment]
> The level of support is impressive, thank you! Works perfectly this time.

Honestly it a dumb bug that i've caused by not testing the code, at least I'm thankful someone caught it and reported it ;p
