### ISSUE TITLE
[AUR] XAVA-git Runtime Error

### ISSUE THREAD

**Issue by cirfis** [nikp123/xava#52]
Good morning! Upon the most recent AUR update to xava-git this unusual error occurred:

`X Error of failed request:  BadValue (integer parameter out of range for operation)`
`  Major opcode of failed request:  152 (GLX)`
`  Minor opcode of failed request:  3 (X_GLXCreateContext)`
`  Value in failed request:  0x0`
`  Serial number of failed request:  54`
`  Current serial number in output stream:  55`

**Comment by nikp123** [comment]
Cannot reproduce with the default config, can you give me the version number ```./xava -v``` and your config file.

**Comment by cirfis** [comment]
I tried reverting to default config and still no dice, same error. Probably something in my setup, but I've no idea what. The only *known* change was xava version.
 
  - xava 0.7.1.1

**Comment by cirfis** [comment]
My apologies. Reboot fixed the issue. Closing as solved.

**Comment by nikp123** [comment]
yep i'm guessing some dependency got messed up during the update
