### ISSUE TITLE
Unable to update AUR package 

### ISSUE THREAD

**Issue by bluebyt** [nikp123/xava#62]
I tried to update Aur package, but Yay keep telling me that a new version  0.7.1.1.r6.ge1d52fa-1 is available, but it never update.
 ```
yay
[sudo] password for bluebyt: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
:: 1 package to upgrade/install.
1  aur/xava-git  0.7.1.1.r0.gd0ccf97-1 -> 0.7.1.1.r6.ge1d52fa-1
```
See log file:
https://pastebin.com/cz2XVzxF

I tried to remove the cache of Aur package and remove the package itself. 
```
yay -Sc 
yay -R xava-git
```
Then I installed it again. 
```
yay xava-git
1 aur/xava-git 0.7.1.1.r6.ge1d52fa-1 (+3 0.00) 
    X11 Audio Visualizer for Alsa/Pulseaudio/FIFO
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```

After installed it, yay want to update it again
```
 yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
:: 1 package to upgrade/install.
1  aur/xava-git  0.7.1.1.r0.gd0ccf97-1 -> 0.7.1.1.r6.ge1d52fa-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
```

**Comment by nikp123** [comment]
Have you tried removinf the yay cache directory manually?

**Comment by bluebyt** [comment]
I just tried to removed the directory: 
/home/bluebyt/.cache/yay/xava-git/

and then run yay,  i have the same result, yay ask me again to upgrade on package xava.

 1 package to upgrade/install.
1  aur/xava-git  0.7.1.1.r0.gd0ccf97-1 -> 0.7.1.1.r6.ge1d52fa-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems

**Comment by nikp123** [comment]
can you upgrade xava in that case, after you've cleared yay's build cache?

**Comment by bluebyt** [comment]
No I tried many time, but yay always gave me this message, after I cleared the cache and tried to upgrade again.
1 package to upgrade/install.
1 aur/xava-git 0.7.1.1.r0.gd0ccf97-1 -> 0.7.1.1.r6.ge1d52fa-1

**Comment by bluebyt** [comment]
I don't know if that can help to understand the problem, but I tried to upgrade with Paru instead of Yay, the result is the same, I end up with version xava-git 0.7.1.1.r0.gd0ccf97-1.

Here the full log:
https://pastebin.com/BDepQaTP

**Comment by nikp123** [comment]
Problem was that the package definition had a newer version then what was generated by the AUR script. Werid, not sure how this happened. Pushed a patch that hopefully fixes that.

**Comment by nikp123** [comment]
![image](https://github.com/user-attachments/assets/a0ebbd6c-121a-48b5-959f-a14125aa539f)

**Comment by bluebyt** [comment]
Ok that solved the problem, thanks!

**Comment by bluebyt** [comment]
It happen again:
yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
 -> Packages not in AUR: nwg-look-bin
:: 1 package to upgrade/install.
1  aur/xava-git  0.7.1.1.r0.g621e384-1 -> 0.7.1.1.r0.gd0ccf97-1
