### ISSUE TITLE
xava doesn't start anymore (Address boundary error)

### ISSUE THREAD

**Issue by bluebyt** [nikp123/xava#64]
xava doesn't start anymore

xava -v
xava 0.7.1.1

```
xava &
fish: Job 1, 'xava &' terminated by signal SIGSEGV (Address boundary error)
```
gdb xava
https://pastebin.com/LpFjGtwF

config
https://pastebin.com/fPVYZUkG

**Comment by nikp123** [comment]
I did a change to how Wayland works without realizing it (despite me leaving a comment there), now it should work.

**Comment by bluebyt** [comment]
Are you going to update xava-git or I have to compile it by myself?
Thanks for the fix btw!

**Comment by bluebyt** [comment]
If I run yay now, there is no package to update.

**Comment by nikp123** [comment]
> If I run yay now, there is no package xava-git to update.

Seems to be actually intended behaviour on for yay at least, you need to specify the ```--devel``` flag along with the rest of your yay command for it to fetch the current commit.

**Comment by bluebyt** [comment]
Thank you, I didn't know that! it works!
