### ISSUE TITLE
Feature request: Add support for Xresources

### ISSUE THREAD

**Issue by sabrehagen** [nikp123/xava#8]
It would be great if xava could support colours defined in [Xresources](https://wiki.archlinux.org/index.php/X_resources).

**Comment by nikp123** [comment]
Good idea, however I do not have much free time now, so updates will be slow (school, etc.)
Also should it read ``*colorN: #ffffff`` or ``XAVA*colorN: #ffffff``, so as to match with the terminal color scheme or not?

Also ``foreground = default`` behavior is kind of dumb and buggy, so this is the perfect chance to override this.

**Comment by sabrehagen** [comment]
> Also should it read `*colorN: #ffffff` or `XAVA*colorN: #ffffff`, so as to match with the terminal color scheme or not?

Exactly, that's the goal :)

**Comment by nikp123** [comment]
so ``*colorN: #ffffff`` it is

**Comment by nikp123** [comment]
for future me that has time, [look this up](https://tronche.com/gui/x/xlib/resource-manager/matching-rules.html)

**Comment by nikp123** [comment]
Done.
