### ISSUE TITLE
config file empty

### ISSUE THREAD

**Issue by Suyashtnt** [nikp123/xava#9]
by reading the readme.md, it seam like there must be something in the config file but there is nothing, using gedit on pop os 19.10. If there is nothing please add some sort of preset in the readme or in this post. Thanks!

**Comment by nikp123** [comment]
have you (``make install``) installed or just compiled and ran the program?

**Comment by nikp123** [comment]
Remove the file ``/home/$USER/.config/xava/config``, build and reinstall the new version.

**Comment by Suyashtnt** [comment]
I’ll do so once I’m back on Linux(reinstalling)

**Comment by Suyashtnt** [comment]
and it worked! thanks
